FROM php:8.0-apache

COPY . /var/www

RUN apt-get update && \
    apt-get install -y \
        nano

COPY conf/vhost.conf /etc/apache2/sites-available/000-default.conf
COPY conf/apache.conf /etc/apache2/conf-available/z-app.conf

RUN a2enconf z-app

